version: '3.7'

services:

  app:
    restart: always
    build:
      context: "./app"
      args:
        JAR_FILE: "target/app.jar"
    ports:
      - "8080:8080"
    environment:
      - "CONSUL_HOST=consul"
      - "CONSUL_PORT=8500"
      - "LOGGING_FILE_PATH=/logs"
    container_name: app
    volumes:
      - log_app_volume:/logs

  app-log-fw:
    image: splunk/universalforwarder:8.0
    hostname: app-log-fw
    environment:
      - "SPLUNK_START_ARGS=--accept-license --answer-yes --name uf"
      - "SPLUNK_STANDALONE_URL=splunk:9997"
      - "SPLUNK_USER=root"
      - "SPLUNK_ADD=monitor /logs"
      - "SPLUNK_PASSWORD=password"
    restart: always
    depends_on:
      - app
    volumes:
      - log_app_volume:/logs

volumes:
  log_app_volume:
