version: '3.7'

services:

  provider:
    restart: on-failure
    build:
      context: "./provider"
      args:
        JAR_FILE: "target/provider.jar"
    ports:
      - "8085-8095:8080"
    environment:
      - "CONSUL_HOST=consul"
      - "CONSUL_PORT=8500"
      - "LOGGING_FILE_PATH=/logs"
    volumes:
      - log_provider_volume:/logs

  provider-log-fw:
    image: splunk/universalforwarder:7.3.0
    environment:
      - "SPLUNK_START_ARGS=--accept-license --answer-yes --name uf"
      - "SPLUNK_STANDALONE_URL=splunk:9997"
      - "SPLUNK_USER=root"
      - "SPLUNK_ADD=monitor /logs"
      - "SPLUNK_PASSWORD=password"
    restart: always
    depends_on:
      - provider
    volumes:
      - log_provider_volume:/logs

volumes:
  log_provider_volume:
