provider:
  settings:
    prime-size: ${PRIME_SIZE}
    instance-id: ${spring.cloud.consul.discovery.instance-id}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.apache: WARN
    it.minetti: DEBUG

feign:
  hystrix:
    enabled: true

spring:
  main:
    banner-mode: OFF