
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

logging:
  level:
    root: INFO
    com.netflix: WARN
    com.netflix.config.sources.URLConfigurationSource: ERROR
    org.apache: WARN
    org.springframework: WARN
    it.minetti: DEBUG

spring:
  main:
    banner-mode: OFF
